/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedRecipesIndexRouteImport } from './routes/_authed/recipes/index'
import { Route as AuthedPourOverIndexRouteImport } from './routes/_authed/pour-over/index'
import { Route as AuthedFrenchPressIndexRouteImport } from './routes/_authed/french-press/index'
import { Route as AuthedEspressoIndexRouteImport } from './routes/_authed/espresso/index'
import { Route as AuthedAeropressIndexRouteImport } from './routes/_authed/aeropress/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedRecipesRecipeIdRouteImport } from './routes/_authed/recipes/$recipeId'
import { Route as AuthedPourOverNewRouteImport } from './routes/_authed/pour-over/new'
import { Route as AuthedFrenchPressNewRouteImport } from './routes/_authed/french-press/new'
import { Route as AuthedEspressoNewRouteImport } from './routes/_authed/espresso/new'
import { Route as AuthedEspressoShotIdRouteImport } from './routes/_authed/espresso/$shotId'
import { Route as AuthedAeropressNewRouteImport } from './routes/_authed/aeropress/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecipesIndexRoute = AuthedRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPourOverIndexRoute = AuthedPourOverIndexRouteImport.update({
  id: '/pour-over/',
  path: '/pour-over/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFrenchPressIndexRoute = AuthedFrenchPressIndexRouteImport.update({
  id: '/french-press/',
  path: '/french-press/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEspressoIndexRoute = AuthedEspressoIndexRouteImport.update({
  id: '/espresso/',
  path: '/espresso/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAeropressIndexRoute = AuthedAeropressIndexRouteImport.update({
  id: '/aeropress/',
  path: '/aeropress/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRecipesRecipeIdRoute = AuthedRecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPourOverNewRoute = AuthedPourOverNewRouteImport.update({
  id: '/pour-over/new',
  path: '/pour-over/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFrenchPressNewRoute = AuthedFrenchPressNewRouteImport.update({
  id: '/french-press/new',
  path: '/french-press/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEspressoNewRoute = AuthedEspressoNewRouteImport.update({
  id: '/espresso/new',
  path: '/espresso/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEspressoShotIdRoute = AuthedEspressoShotIdRouteImport.update({
  id: '/espresso/$shotId',
  path: '/espresso/$shotId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAeropressNewRoute = AuthedAeropressNewRouteImport.update({
  id: '/aeropress/new',
  path: '/aeropress/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthedSettingsRoute
  '/aeropress/new': typeof AuthedAeropressNewRoute
  '/espresso/$shotId': typeof AuthedEspressoShotIdRoute
  '/espresso/new': typeof AuthedEspressoNewRoute
  '/french-press/new': typeof AuthedFrenchPressNewRoute
  '/pour-over/new': typeof AuthedPourOverNewRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/aeropress/': typeof AuthedAeropressIndexRoute
  '/espresso/': typeof AuthedEspressoIndexRoute
  '/french-press/': typeof AuthedFrenchPressIndexRoute
  '/pour-over/': typeof AuthedPourOverIndexRoute
  '/recipes/': typeof AuthedRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/aeropress/new': typeof AuthedAeropressNewRoute
  '/espresso/$shotId': typeof AuthedEspressoShotIdRoute
  '/espresso/new': typeof AuthedEspressoNewRoute
  '/french-press/new': typeof AuthedFrenchPressNewRoute
  '/pour-over/new': typeof AuthedPourOverNewRoute
  '/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/aeropress': typeof AuthedAeropressIndexRoute
  '/espresso': typeof AuthedEspressoIndexRoute
  '/french-press': typeof AuthedFrenchPressIndexRoute
  '/pour-over': typeof AuthedPourOverIndexRoute
  '/recipes': typeof AuthedRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/aeropress/new': typeof AuthedAeropressNewRoute
  '/_authed/espresso/$shotId': typeof AuthedEspressoShotIdRoute
  '/_authed/espresso/new': typeof AuthedEspressoNewRoute
  '/_authed/french-press/new': typeof AuthedFrenchPressNewRoute
  '/_authed/pour-over/new': typeof AuthedPourOverNewRoute
  '/_authed/recipes/$recipeId': typeof AuthedRecipesRecipeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/aeropress/': typeof AuthedAeropressIndexRoute
  '/_authed/espresso/': typeof AuthedEspressoIndexRoute
  '/_authed/french-press/': typeof AuthedFrenchPressIndexRoute
  '/_authed/pour-over/': typeof AuthedPourOverIndexRoute
  '/_authed/recipes/': typeof AuthedRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/aeropress/new'
    | '/espresso/$shotId'
    | '/espresso/new'
    | '/french-press/new'
    | '/pour-over/new'
    | '/recipes/$recipeId'
    | '/api/auth/$'
    | '/aeropress/'
    | '/espresso/'
    | '/french-press/'
    | '/pour-over/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/aeropress/new'
    | '/espresso/$shotId'
    | '/espresso/new'
    | '/french-press/new'
    | '/pour-over/new'
    | '/recipes/$recipeId'
    | '/api/auth/$'
    | '/aeropress'
    | '/espresso'
    | '/french-press'
    | '/pour-over'
    | '/recipes'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/aeropress/new'
    | '/_authed/espresso/$shotId'
    | '/_authed/espresso/new'
    | '/_authed/french-press/new'
    | '/_authed/pour-over/new'
    | '/_authed/recipes/$recipeId'
    | '/api/auth/$'
    | '/_authed/aeropress/'
    | '/_authed/espresso/'
    | '/_authed/french-press/'
    | '/_authed/pour-over/'
    | '/_authed/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recipes/': {
      id: '/_authed/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthedRecipesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pour-over/': {
      id: '/_authed/pour-over/'
      path: '/pour-over'
      fullPath: '/pour-over/'
      preLoaderRoute: typeof AuthedPourOverIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/french-press/': {
      id: '/_authed/french-press/'
      path: '/french-press'
      fullPath: '/french-press/'
      preLoaderRoute: typeof AuthedFrenchPressIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/espresso/': {
      id: '/_authed/espresso/'
      path: '/espresso'
      fullPath: '/espresso/'
      preLoaderRoute: typeof AuthedEspressoIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/aeropress/': {
      id: '/_authed/aeropress/'
      path: '/aeropress'
      fullPath: '/aeropress/'
      preLoaderRoute: typeof AuthedAeropressIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/recipes/$recipeId': {
      id: '/_authed/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthedRecipesRecipeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pour-over/new': {
      id: '/_authed/pour-over/new'
      path: '/pour-over/new'
      fullPath: '/pour-over/new'
      preLoaderRoute: typeof AuthedPourOverNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/french-press/new': {
      id: '/_authed/french-press/new'
      path: '/french-press/new'
      fullPath: '/french-press/new'
      preLoaderRoute: typeof AuthedFrenchPressNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/espresso/new': {
      id: '/_authed/espresso/new'
      path: '/espresso/new'
      fullPath: '/espresso/new'
      preLoaderRoute: typeof AuthedEspressoNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/espresso/$shotId': {
      id: '/_authed/espresso/$shotId'
      path: '/espresso/$shotId'
      fullPath: '/espresso/$shotId'
      preLoaderRoute: typeof AuthedEspressoShotIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/aeropress/new': {
      id: '/_authed/aeropress/new'
      path: '/aeropress/new'
      fullPath: '/aeropress/new'
      preLoaderRoute: typeof AuthedAeropressNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAeropressNewRoute: typeof AuthedAeropressNewRoute
  AuthedEspressoShotIdRoute: typeof AuthedEspressoShotIdRoute
  AuthedEspressoNewRoute: typeof AuthedEspressoNewRoute
  AuthedFrenchPressNewRoute: typeof AuthedFrenchPressNewRoute
  AuthedPourOverNewRoute: typeof AuthedPourOverNewRoute
  AuthedRecipesRecipeIdRoute: typeof AuthedRecipesRecipeIdRoute
  AuthedAeropressIndexRoute: typeof AuthedAeropressIndexRoute
  AuthedEspressoIndexRoute: typeof AuthedEspressoIndexRoute
  AuthedFrenchPressIndexRoute: typeof AuthedFrenchPressIndexRoute
  AuthedPourOverIndexRoute: typeof AuthedPourOverIndexRoute
  AuthedRecipesIndexRoute: typeof AuthedRecipesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAeropressNewRoute: AuthedAeropressNewRoute,
  AuthedEspressoShotIdRoute: AuthedEspressoShotIdRoute,
  AuthedEspressoNewRoute: AuthedEspressoNewRoute,
  AuthedFrenchPressNewRoute: AuthedFrenchPressNewRoute,
  AuthedPourOverNewRoute: AuthedPourOverNewRoute,
  AuthedRecipesRecipeIdRoute: AuthedRecipesRecipeIdRoute,
  AuthedAeropressIndexRoute: AuthedAeropressIndexRoute,
  AuthedEspressoIndexRoute: AuthedEspressoIndexRoute,
  AuthedFrenchPressIndexRoute: AuthedFrenchPressIndexRoute,
  AuthedPourOverIndexRoute: AuthedPourOverIndexRoute,
  AuthedRecipesIndexRoute: AuthedRecipesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
